### ISSUE TITLE
Conditional Modifiers

### ISSUE THREAD

**Issue by shocklateboy92** [shocklateboy92/psychic-bear#11]
TurboBatman had buttons for conditions that could determine if certain Bonuses were active or not. This was useful for active abilities / commonly cast spells.

This will need something similar soon.

**Comment by shocklateboy92** [comment]
In branch 'conditionals2', there is currently a reference view for conditions (all BonusSources) with a button per condition.
Consider using disabled buttons for permanent bonuses, instead of not displaying them at all.

**Comment by shocklateboy92** [comment]
Also, add a property to BonusSource called 'effects' that's also QQmlListProperty<Bonus>, and auto link Bonus source/target both ways. 
(This will help track links in future).

**Comment by ZeDestructor** [comment]
Fixed in be135d663a42b64ceb7db635b9b7529d586c4ae6
